[build]
target = "x86_64-unknown-uefi"
restflags = ["-Cforce-unwind-tables", "-Cforce-frame-pointers", "-Cno-redzone"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "uefi")']
runner = "bash scripts/launch_qemu.sh"

# [target.x86_64-unknown-uefi]
# rustflags = ["-Cforce-unwind-tables", "-Cforce-frame-pointers", "-Cno-redzone"]
# runner = "bash scripts/launch_qemu.sh"

# [alias]
# uefi-build = "build -Z build-std=core,compiler_builtins,alloc,panic_abort -Z build-std-features=compiler-builtins-mem --target x86_64-unknown-uefi"
# uefi-run   = "run   -Z build-std=core,compiler_builtins,alloc,panic_abort -Z build-std-features=compiler-builtins-mem --target x86_64-unknown-uefi"
